version: '3'

services:
  flux:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${NODE_PORT}
    volumes:
      - ./.env:/app/.env
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
