version: "3"

services:
  flux:
    build: .
    environment:
      VIRTUAL_HOST: flux.camino.beta.gouv.fr
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: flux.camino.beta.gouv.fr
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      NODE_PORT: ${NODE_PORT}
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy
