# Démarrage du serveur à http://localhost:${NODE_PORT}
version: '3'

services:
  flux:
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      NODE_PORT: ${NODE_PORT}
    expose:
      - ${NODE_PORT}
    volumes:
      - ./.env:/app/.env
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
